### ISSUE TITLE
Checklist 

### ISSUE THREAD

**Issue by min20120907** [bebo1010/sokoban#4]
### Pending Working List
- [ ] Adding checkdeath function
- [x] Adding 3~10 Stages
- [x] Restart function
- [x] Real-time Timer
- [x] Real-time step counter
- [x]  Close Function

**Comment by bebo1010** [comment]
level data completed
